#!/usr/bin/env python3
"""Generate Odin rectangle constants from an rGuiLayout 4.0 text file."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def identifier(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not value or value[0].isdigit():
        value = "control_" + value
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--package", default="layout", help="generated Odin package name")
    args = parser.parse_args()

    ref_x = ref_y = 0.0
    controls: list[tuple[str, float, float, float, float, str]] = []
    anchors: dict[int, tuple[float, float]] = {0: (0.0, 0.0)}

    for raw_line in args.input.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split(maxsplit=9)
        if fields[0] == "r":
            ref_x, ref_y, width, height = map(float, fields[1:5])
            anchors[0] = (ref_x, ref_y)
            reference = (width, height)
        elif fields[0] == "a":
            anchor_id = int(fields[1])
            anchors[anchor_id] = (ref_x + float(fields[3]), ref_y + float(fields[4]))
        elif fields[0] == "c":
            _, _, _, name, x, y, width, height, anchor_id, *tail = fields
            ax, ay = anchors[int(anchor_id)]
            text = tail[0] if tail else ""
            controls.append((identifier(name), ax + float(x), ay + float(y), float(width), float(height), text))

    if "reference" not in locals():
        raise SystemExit(f"{args.input}: missing reference-window record")

    def number(value: float) -> str:
        return str(int(value)) if value.is_integer() else repr(value)

    lines = [
        "// Code generated by tools/rgl_to_odin.py; DO NOT EDIT.",
        f"// Source: {args.input.as_posix()}",
        f"package {identifier(args.package)}",
        "",
        'import rl "vendor:raylib/v55"',
        "",
        f"REFERENCE_WIDTH :: f32({number(reference[0])})",
        f"REFERENCE_HEIGHT :: f32({number(reference[1])})",
        "",
    ]
    for name, x, y, width, height, text in controls:
        lines.append(
            f"{name} :: rl.Rectangle{{{number(x)}, {number(y)}, {number(width)}, {number(height)}}}"
        )
        lines.append(f"{name}_TEXT :: cstring({json.dumps(text)})")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
